/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/v2/pia": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Aircrafts with PIA addresses (Privacy ICAO Address)
     * @description Returns all aircraft with [PIA](https://nbaa.org/aircraft-operations/security/privacy/privacy-icao-address-pia/) addresses.
     */
    get: operations["v2_pia_v2_pia_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v2/mil": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Military registered aircrafts
     * @description Returns all military registered aircraft.
     */
    get: operations["v2_mil_v2_mil_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v2/ladd": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Aircrafts on LADD (Limiting Aircraft Data Displayed)
     * @description Returns all aircrafts on [LADD](https://www.faa.gov/pilots/ladd) filter.
     */
    get: operations["v2_ladd_v2_ladd_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v2/sqk/{squawk}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Aircrafts with specific squawk (1200, 7700, etc.)
     * @description Returns aircraft filtered by "squawk" [transponder code](https://en.wikipedia.org/wiki/List_of_transponder_codes).
     */
    get: operations["v2_squawk_filter_v2_sqk__squawk__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v2/squawk/{squawk}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Aircrafts with specific squawk (1200, 7700, etc.)
     * @description Returns aircraft filtered by "squawk" [transponder code](https://en.wikipedia.org/wiki/List_of_transponder_codes).
     */
    get: operations["v2_squawk_filter_v2_squawk__squawk__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v2/type/{aircraft_type}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Aircrafts of specific type (A320, B738)
     * @description Returns aircraft filtered by [aircraft type designator code](https://en.wikipedia.org/wiki/List_of_aircraft_type_designators).
     */
    get: operations["v2_type_filter_v2_type__aircraft_type__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v2/reg/{registration}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Aircrafts with specific registration (G-KELS)
     * @description Returns aircraft filtered by [aircarft registration code](https://en.wikipedia.org/wiki/Aircraft_registration).
     */
    get: operations["v2_reg_filter_v2_reg__registration__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v2/registration/{registration}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Aircrafts with specific registration (G-KELS)
     * @description Returns aircraft filtered by [aircarft registration code](https://en.wikipedia.org/wiki/Aircraft_registration).
     */
    get: operations["v2_reg_filter_v2_registration__registration__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v2/icao/{icao_hex}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Aircrafts with specific transponder hex code (4CA87C)
     * @description Returns aircraft filtered by [transponder hex code](https://en.wikipedia.org/wiki/Aviation_transponder_interrogation_modes#ICAO_24-bit_address).
     */
    get: operations["v2_hex_filter_v2_icao__icao_hex__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v2/hex/{icao_hex}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Aircrafts with specific transponder hex code (4CA87C)
     * @description Returns aircraft filtered by [transponder hex code](https://en.wikipedia.org/wiki/Aviation_transponder_interrogation_modes#ICAO_24-bit_address).
     */
    get: operations["v2_hex_filter_v2_hex__icao_hex__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v2/callsign/{callsign}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Aircrafts with specific callsign (JBU1942)
     * @description Returns aircraft filtered by [callsign](https://en.wikipedia.org/wiki/Aviation_call_signs).
     */
    get: operations["v2_callsign_filter_v2_callsign__callsign__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v2/lat/{lat}/lon/{lon}/dist/{radius}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Aircrafts surrounding a point (lat, lon) up to 250nm
     * @description Returns aircraft located in a circle described by the latitude and longtidude of its center and its radius.
     */
    get: operations["v2_point_v2_lat__lat__lon__lon__dist__radius__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v2/point/{lat}/{lon}/{radius}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Aircrafts surrounding a point (lat, lon) up to 250nm
     * @description Returns aircraft located in a circle described by the latitude and longtidude of its center and its radius.
     */
    get: operations["v2_point_v2_point__lat___lon___radius__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v2/closest/{lat}/{lon}/{radius}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Single aircraft closest to a point (lat, lon)
     * @description Returns the closest aircraft to a point described by the latitude and longtidude within a radius up to 250nm.
     */
    get: operations["v2_closest_v2_closest__lat___lon___radius__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/0/airport/{icao}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Airports by ICAO
     * @description Data by https://github.com/vradarserver/standing-data/
     */
    get: operations["api_airport_api_0_airport__icao__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/0/routeset": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Api Routeset */
    post: operations["api_routeset_api_0_routeset_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/0/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Information about your receiver and global stats */
    get: operations["api_me_0_me_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/0/my": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** My Map redirect based on IP */
    get: operations["api_my_0_my_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** PlaneInstance */
    PlaneInstance: {
      /** Callsign */
      callsign: string;
      /** Lat */
      lat: number;
      /** Lng */
      lng: number;
    };
    /** PlaneList */
    PlaneList: {
      /** Planes */
      planes?: components["schemas"]["PlaneInstance"][] | null;
    };
    /** V2Response_AcItem */
    V2Response_AcItem: {
      /** Alert */
      alert?: number | null;
      /** Alt Baro */
      alt_baro?: number | string | null;
      /** Alt Geom */
      alt_geom?: number | null;
      /** Baro Rate */
      baro_rate?: number | null;
      /** Category */
      category?: string | null;
      /** Emergency */
      emergency?: string | null;
      /** Flight */
      flight?: string | null;
      /** Gs */
      gs?: number | null;
      /** Gva */
      gva?: number | null;
      /** Hex */
      hex: string;
      /** Lat */
      lat?: number | null;
      /** Lon */
      lon?: number | null;
      /** Messages */
      messages: number;
      /** Mlat */
      mlat: string[];
      /** Nac P */
      nac_p?: number | null;
      /** Nac V */
      nac_v?: number | null;
      /** Nav Altitude Mcp */
      nav_altitude_mcp?: number | null;
      /** Nav Heading */
      nav_heading?: number | null;
      /** Nav Qnh */
      nav_qnh?: number | null;
      /** Nic */
      nic?: number | null;
      /** Nic Baro */
      nic_baro?: number | null;
      /** R */
      r?: string | null;
      /** Rc */
      rc?: number | null;
      /** Rssi */
      rssi: number;
      /** Sda */
      sda?: number | null;
      /** Seen */
      seen: number;
      /** Seen Pos */
      seen_pos?: number | null;
      /** Sil */
      sil?: number | null;
      /** Sil Type */
      sil_type?: string | null;
      /** Spi */
      spi?: number | null;
      /** Squawk */
      squawk?: string | null;
      /** T */
      t?: string | null;
      /** Tisb */
      tisb: string[];
      /** Track */
      track?: number | null;
      /** Type */
      type: string;
      /** Version */
      version?: number | null;
      /** Geom Rate */
      geom_rate?: number | null;
      /** Dbflags */
      dbFlags?: number | null;
      /** Nav Modes */
      nav_modes?: string[] | null;
      /** True Heading */
      true_heading?: number | null;
      /** Ias */
      ias?: number | null;
      /** Mach */
      mach?: number | null;
      /** Mag Heading */
      mag_heading?: number | null;
      /** Oat */
      oat?: number | null;
      /** Roll */
      roll?: number | null;
      /** Tas */
      tas?: number | null;
      /** Tat */
      tat?: number | null;
      /** Track Rate */
      track_rate?: number | null;
      /** Wd */
      wd?: number | null;
      /** Ws */
      ws?: number | null;
      /** Gpsokbefore */
      gpsOkBefore?: number | null;
      /** Gpsoklat */
      gpsOkLat?: number | null;
      /** Gpsoklon */
      gpsOkLon?: number | null;
      lastPosition?: components["schemas"]["V2Response_LastPosition"] | null;
      /** Rr Lat */
      rr_lat?: number | null;
      /** Rr Lon */
      rr_lon?: number | null;
      /** Calc Track */
      calc_track?: number | null;
      /** Nav Altitude Fms */
      nav_altitude_fms?: number | null;
    };
    /** V2Response_LastPosition */
    V2Response_LastPosition: {
      /** Lat */
      lat: number;
      /** Lon */
      lon: number;
      /** Nic */
      nic: number;
      /** Rc */
      rc: number;
      /** Seen Pos */
      seen_pos: number;
    };
    /** V2Response_Model */
    V2Response_Model: {
      /** Ac */
      ac: components["schemas"]["V2Response_AcItem"][];
      /** Ctime */
      ctime: number;
      /** Msg */
      msg: string;
      /** Now */
      now: number;
      /** Ptime */
      ptime: number;
      /** Total */
      total: number;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  v2_pia_v2_pia_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["V2Response_Model"];
        };
      };
    };
  };
  v2_mil_v2_mil_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["V2Response_Model"];
        };
      };
    };
  };
  v2_ladd_v2_ladd_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["V2Response_Model"];
        };
      };
    };
  };
  v2_squawk_filter_v2_sqk__squawk__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @example 1200 */
        squawk: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["V2Response_Model"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  v2_squawk_filter_v2_squawk__squawk__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @example 1200 */
        squawk: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["V2Response_Model"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  v2_type_filter_v2_type__aircraft_type__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @example A320 */
        aircraft_type: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["V2Response_Model"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  v2_reg_filter_v2_reg__registration__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @example G-KELS */
        registration: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["V2Response_Model"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  v2_reg_filter_v2_registration__registration__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @example G-KELS */
        registration: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["V2Response_Model"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  v2_hex_filter_v2_icao__icao_hex__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @example 4CA87C */
        icao_hex: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["V2Response_Model"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  v2_hex_filter_v2_hex__icao_hex__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @example 4CA87C */
        icao_hex: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["V2Response_Model"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  v2_callsign_filter_v2_callsign__callsign__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @example JBU1942 */
        callsign: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["V2Response_Model"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  v2_point_v2_lat__lat__lon__lon__dist__radius__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @example 51.89508 */
        lat: number;
        /** @example 2.79437 */
        lon: number;
        /** @example 250 */
        radius: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["V2Response_Model"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  v2_point_v2_point__lat___lon___radius__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @example 51.89508 */
        lat: number;
        /** @example 2.79437 */
        lon: number;
        /** @example 250 */
        radius: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["V2Response_Model"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  v2_closest_v2_closest__lat___lon___radius__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @example 51.89508 */
        lat: number;
        /** @example 2.79437 */
        lon: number;
        /** @example 250 */
        radius: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["V2Response_Model"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  api_airport_api_0_airport__icao__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        icao: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": string;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  api_routeset_api_0_routeset_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PlaneList"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": string;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  api_me_0_me_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": string;
        };
      };
    };
  };
  api_my_0_my_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
}
